spring:
    data:
        mongodb:
            uri: ${SPRING_DATASOURCE_URL}
            database: pokemons
            username: ${SPRING_DATASOURCE_USERNAME}
            password: ${SPRING_DATASOURCE_PASSWORD}