spring:
    data:
        mongodb:
            uri: ${SPRING_DATASOURCE_URL}
            database: ${SPRING_DATABASE_NAME}
            username: ${SPRING_DATASOURCE_USERNAME}
            password: ${SPRING_DATASOURCE_PASSWORD}